default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>
  timeout: 5000

development:
  <<: *default
  host: localhost
  username: root
  password: root
  database: ejercicio_pagos